from utils.config import (
    AZURE_OPENAI_ENDPOINT,
    AZURE_OPENAI_API_KEY,
    AZURE_OPENAI_DEPLOYMENT_NAME,
    AZURE_COGNITIVE_SEARCH_ENDPOINT,
    AZURE_COGNITIVE_SEARCH_ADMIN_KEY,
    AZURE_COGNITIVE_SEARCH_INDEX_NAME,
    LOG_LEVEL,
)

def test_config():
    print("Testing configuration variables...")
    print(f"AZURE_OPENAI_ENDPOINT: {AZURE_OPENAI_ENDPOINT}")
    print(f"AZURE_OPENAI_API_KEY: {AZURE_OPENAI_API_KEY}")
    print(f"AZURE_OPENAI_DEPLOYMENT_NAME: {AZURE_OPENAI_DEPLOYMENT_NAME}")
    print(f"AZURE_COGNITIVE_SEARCH_ENDPOINT: {AZURE_COGNITIVE_SEARCH_ENDPOINT}")
    print(f"AZURE_COGNITIVE_SEARCH_ADMIN_KEY: {AZURE_COGNITIVE_SEARCH_ADMIN_KEY}")
    print(f"AZURE_COGNITIVE_SEARCH_INDEX_NAME: {AZURE_COGNITIVE_SEARCH_INDEX_NAME}")
    print(f"LOG_LEVEL: {LOG_LEVEL}")

if __name__ == "__main__":
    test_config()
